{   'central': {   'completex': {   'cols': {   },
                                    'details': 'normal',
                                    'edit': 'vbox_saisie1',
                                    'edit tab': '1',
                                    'from': 'complete     ',
                                    'id_main': 'id_livre',
                                    'result': 'complete',
                                    'table': 'complete',
                                    'words': 'mots,'}},
    'combobox': {   'Local': {   'combobox': 'combo_localisation',
                                 'entry': '',
                                 'group': 'cotes',
                                 'query': 'select distinct localisation from complete'},
                    'format': {   'combobox': 'combo_format',
                                  'entry': '',
                                  'group': 'cotes',
                                  'query': 'select distinct format from complete'},
                    'notes': {   'combobox': 'combo_notes',
                                 'group': 'cotes',
                                 'query': 'select distinct notes from complete'},
                    'num\xc3\xa9ro': {   'combobox': 'entry_num', 'group': 'cotes'},
                    'section': {   'combobox': 'combo_section',
                                   'entry': '',
                                   'group': 'cotes',
                                   'query': 'select distinct section from complete'}},
    'details': {   'normal': {   'container': 'vbox2', 'details_tab': '1'}},
    'edit_lists': {   'test1': {   'cols': {   0: {   'field': 'fonction',
                                                      'title': 'fonction',
                                                      'width': '100'}},
                                   'details': '[presentation]',
                                   'periph_def': 'personnesx',
                                   'width': '200'}},
    'gateway_data': {   'chartreuses': {   'cols': {   }, 'gateway': {   }},
                        'collections': {   'cols': {   0: {   'field': 'numero',
                                                              'title': 'Num\xc3\xa9ro',
                                                              'type': 'list',
                                                              'width': 80}},
                                           'gateway': 'serie'},
                        'langues': {   'cols': {   }, 'gateway': {   }},
                        'personnes': {   'cols': {   0: {   'field': 'fonction',
                                                            'title': 'fonction',
                                                            'type': 'list',
                                                            'width': '150'},
                                                     1: {   'field': 'anonyme',
                                                            'title': 'Ano',
                                                            'type': 'list',
                                                            'width': '80'}},
                                         'gateway': 'concerne',
                                         'width': '200'},
                        'themes': {   'cols': {   }, 'gateway': {   }}},
    'ini': {   'Hpaned': {   'hpaned1': 446,
                             'hpaned10': 494,
                             'hpaned3': 481,
                             'hpaned5': 690,
                             'hpaned6': 623,
                             'hpaned7': 454,
                             'hpaned8': 747,
                             'hpaned9': 623,
                             's_hpaned4': 302,
                             's_vpaned1': 398},
               'database': {   'autobackup': 0,
                               'central_table': None,
                               'database': 'maggy',
                               'deleted_records': 'fichessuppr',
                               'from': None,
                               'host': '192.168.1.4',
                               'main_field': None,
                               'modified_field': 'datemodification',
                               'mysql': 'C:\\Prog2\\Mysql\\Mysql corrige',
                               'order_field': 'ordre',
                               'pass': '',
                               'sqlite': '',
                               'user': 'dysmas'},
               'gui': {   'language': None, 'start_tab': '2'},
               'input': {   'container': None, 'field_indicator': '@', 'separator': '#'},
               'lists': {   'font': 'Arial',
                            'font_size': '10',
                            'line_height': '18',
                            'max_lines': '150',
                            'type_delay': '1000'},
               'output': {   'field_separator': ' ;'},
               'position': {   'null': {   'h': 582, 'w': 277, 'x': 842, 'y': 101},
                               's_columns': {   'h': 391, 'w': 158, 'x': 1084, 'y': 233},
                               's_combine': {   'h': 420, 'w': 392, 'x': 176, 'y': 176},
                               's_history': {   'h': 251, 'w': 467, 'x': 528, 'y': 286},
                               's_options': {   'h': 600, 'w': 800, 'x': 197, 'y': 100},
                               's_requetes': {   'h': 514, 'w': 730, 'x': 181, 'y': 100},
                               's_tri': {   'h': 484, 'w': 342, 'x': 161, 'y': 75},
                               's_window': {   'h': 746, 'w': 1275, 'x': 83, 'y': -8},
                               's_window0': {   'h': 671, 'w': 1024, 'x': -4, 'y': -4},
                               'window0': {   'h': 602, 'w': 51, 'x': 0, 'y': 0},
                               'window1': {   'h': 671, 'w': 1024, 'x': -4, 'y': -4}},
               'zoom1': {   'h': 644, 'w': 990, 'x': 0, 'y': 0},
               'zoom2': {   'h': 144, 'w': 1008, 'x': 8, 'y': 742}},
    'inversion': {   'auteur': {   'central_field': 'auteur',
                                   'condition': 'fonction like "auteur%"',
                                   'content': '',
                                   'invert_field': 'i_auteur',
                                   'table_def': 'personnesx'},
                     'biographie': {   'central_field': 'biographie',
                                       'condition': 'fonction like "biographie%"',
                                       'content': '',
                                       'invert_field': 'i_biographie',
                                       'table_def': 'personnesx'},
                     'collaborateur': {   'central_field': 'collaborateur',
                                          'condition': 'fonction like "collaborateur%"',
                                          'content': '',
                                          'invert_field': 'i_collaborateur',
                                          'table_def': 'personnesx'},
                     'vedette': {   'central_field': 'vedette',
                                    'condition': 'fonction like "vedette%"',
                                    'content': '',
                                    'invert_field': 'i_vedette',
                                    'table_def': 'personnesx'}},
    'periph_tables': {   0: 'personnes',
                         1: 'chartreuses',
                         2: 'langues',
                         3: 'themes',
                         4: 'mots',
                         5: 'requetes'},
    'peripheral': {   'chartreuses': {   'central_def': 'completex',
                                         'cols': '',
                                         'config_name': 'chartreuses',
                                         'gateway': 'maison',
                                         'gateway_fields': [],
                                         'id_type': 'id_chartreuse',
                                         'info': '',
                                         'main_field': 'chartreuse',
                                         'search_lists': 'clist5',
                                         'table': 'chartreuses',
                                         'table_type': 'peripheral2'},
                      'collections': {   'central_def': 'completex',
                                         'cols': '',
                                         'config_name': 'collections',
                                         'gateway': 'serie',
                                         'gateway_fields': ['numero'],
                                         'id_type': 'id_collection',
                                         'info': '',
                                         'main_field': 'collection',
                                         'search_lists': 'sp_collections',
                                         'table': 'collections',
                                         'table_type': 'peripheral2'},
                      'langues': {   'central_def': 'completex',
                                     'cols': None,
                                     'config_name': 'langues',
                                     'gateway': 'parle',
                                     'gateway_fields': [],
                                     'id_type': 'id_langue',
                                     'info': None,
                                     'main_field': 'langue',
                                     'search_lists': 'sp_language',
                                     'table': 'langues',
                                     'table_type': 'peripheral2'},
                      'personnesx': {   'central_def': 'completex',
                                        'cols': {   0: {   'width': '120'},
                                                    1: {   'field': 'fonction',
                                                           'title': 'fonction',
                                                           'type': 'list',
                                                           'width': '60'},
                                                    2: {   'field': 'anonyme',
                                                           'title': 'anonyme',
                                                           'type': 'list',
                                                           'width': '25'}},
                                        'config_name': 'personnesx',
                                        'gateway': 'concerne',
                                        'gateway_fields': ['fonction', 'anonyme'],
                                        'id_type': 'id_personne',
                                        'info': None,
                                        'main_field': 'nom',
                                        'search_lists': 'clist3',
                                        'table': 'personnes',
                                        'table_type': 'peripheral2'},
                      's_predef_queries': {   'central_def': {   },
                                              'cols': None,
                                              'config_name': 's_predef_queries',
                                              'edit': '',
                                              'edit tab': '',
                                              'gateway': '',
                                              'id_main': '',
                                              'id_type': 'id_requete',
                                              'main_field': 'nom',
                                              'table': 'requetes',
                                              'table_type': 'peripheral1'},
                      'themes': {   'central_def': 'completex',
                                    'cols': None,
                                    'config_name': 'themes',
                                    'gateway': 'sujet',
                                    'gateway_fields': [],
                                    'id_type': 'id_theme',
                                    'info': None,
                                    'main_field': 'theme',
                                    'search_lists': 'clist7',
                                    'table': 'themes',
                                    'table_type': 'peripheral2'}},
    'popup': {   'chartreuses': {   'code': '[historique]',
                                    'condition': 'select chartreuse from chartreuses where historique is not null',
                                    'query': '',
                                    'table_def': 'chartreuses',
                                    'type': 'text'},
                 'personnes': {   'code': '[presentation]',
                                  'condition': 'select nom from personnes where presentation is not null',
                                  'query': '',
                                  'table_def': 'personnesx',
                                  'type': 'text'},
                 'photo': {   'code': '', 'condition': '', 'query': 'images', 'type': 'photo'}},
    'print': {   'fiche compl\xc3\xa8te html': {   'after': '  </tbody> </table> <br> </body> </html> ',
                                                   'before': '<html> <head>   <meta content="text/html; charset=UTF-8"  http-equiv="content-type">   <title>fiches completes</title> </head> <body> <table style="text-align: left; width: 100%;" border="1"  cellpadding="2" cellspacing="2">   <tbody> ',
                                                   'code': '    <tr>       <td colspan="1" rowspan="2">[section]<br> [num] <font size="-2">[exposant]<br>       </font>[format]</td>       <td>[g_personnes]</td>     </tr>     <tr>       <td>[titre, after=<br> ][sous_titre, after =<br> ][complement,after=<br> ]<br>       </td>     </tr>     <tr>       <td colspan="2" rowspan="1">[lieu], [editeur], [date], [volumes] vol.,&nbsp; [pages] ,&nbsp;&nbsp; [hauteur] ,&nbsp;&nbsp;&nbsp; [illustrations]</td>     </tr>     <tr>       <td colspan="2" rowspan="1">[traduction, after=<br> ][contenu, after=<br> ][remarques]</td>     </tr> ',
                                                   'extension': 'html  ',
                                                   'type': ''},
                 'test rtf': {   'after': '}        ',
                                 'before': '{\\rtf1 ',
                                 'code': '\\trowd\\trgaph70\\cellx1500\\cellx5000\\cellx11000\\cellx12000\\cellx13500\\cellx15000 \\pard\\intbl [section] [num] [format]\\cell [auteur]\\cell [titre]\\cell \\cell \\cell [siecle] \\cell \\pard\\intbl\\row\\pard ',
                                 'extension': 'rtf',
                                 'type': ''},
                 'texte pur': {   'after': '',
                                  'before': '',
                                  'code': '[section] [num] [format]\t[auteur, after=;] [titre] [date]  ',
                                  'extension': '',
                                  'type': ''}},
    'result': {   'complete': {   'cols': {   0: {   'field': 'complete.id_livre',
                                                     'options': '',
                                                     'title': 'id_livre',
                                                     'visible': '0',
                                                     'width': '40'},
                                              1: {   'alias': '',
                                                     'field': 'section',
                                                     'options': 'pango',
                                                     'title': 'sectionx',
                                                     'visible': '1',
                                                     'width': '80'},
                                              2: {   'field': 'numero',
                                                     'options': '',
                                                     'title': 'numero',
                                                     'visible': '1',
                                                     'width': 70},
                                              3: {   'field': 'exposant',
                                                     'options': '',
                                                     'title': 'exposant',
                                                     'visible': '0',
                                                     'width': '40'},
                                              4: {   'alias': '',
                                                     'field': 'notes',
                                                     'options': '',
                                                     'title': 'notes',
                                                     'visible': '1',
                                                     'width': '80'},
                                              5: {   'field': 'localisation as local',
                                                     'options': '',
                                                     'title': 'local',
                                                     'visible': '0',
                                                     'width': '25'},
                                              6: {   'field': 'g_personnes',
                                                     'options': '',
                                                     'title': 'personnes',
                                                     'visible': '1',
                                                     'width': '280'},
                                              7: {   'alias': '',
                                                     'field': 'titre',
                                                     'options': '',
                                                     'title': 'titre',
                                                     'visible': '1',
                                                     'width': '500'},
                                              8: {   'field': 'traduction',
                                                     'options': '',
                                                     'title': 'traduction',
                                                     'visible': 0,
                                                     'width': 200},
                                              9: {   'field': 'collaborateur',
                                                     'options': '',
                                                     'title': 'collaborateur',
                                                     'visible': 0,
                                                     'width': 200},
                                              10: {   'field': 'vedette',
                                                      'options': '',
                                                      'title': 'vedette',
                                                      'visible': 0,
                                                      'width': 200},
                                              11: {   'field': 'biographie',
                                                      'options': '',
                                                      'title': 'biographie',
                                                      'visible': 0,
                                                      'width': 200},
                                              12: {   'alias': '',
                                                      'field': 'lieu',
                                                      'options': '',
                                                      'title': 'lieu',
                                                      'visible': 0,
                                                      'width': 30},
                                              13: {   'field': 'editeur as \xc3\xa9diteur',
                                                      'options': '',
                                                      'title': '\xc3\xa9diteur',
                                                      'visible': 0,
                                                      'width': 40},
                                              14: {   'alias': '',
                                                      'field': 'annee',
                                                      'options': '',
                                                      'title': 'annee',
                                                      'visible': '1',
                                                      'width': '80'},
                                              15: {   'alias': '',
                                                      'field': 'volumes',
                                                      'options': '',
                                                      'title': 'volumes',
                                                      'visible': '0',
                                                      'width': '30'},
                                              16: {   'field': 'pages',
                                                      'options': '',
                                                      'title': 'pages',
                                                      'visible': 0,
                                                      'width': 20},
                                              17: {   'field': 'illustrations',
                                                      'options': '',
                                                      'title': 'illustrations',
                                                      'visible': 0,
                                                      'width': 40},
                                              18: {   'field': 'hauteur',
                                                      'options': '',
                                                      'title': 'hauteur',
                                                      'visible': 0,
                                                      'width': 40},
                                              19: {   'alias': '',
                                                      'field': 'g_langues as langues',
                                                      'options': '',
                                                      'title': 'langues',
                                                      'visible': '0',
                                                      'width': '40'},
                                              20: {   'alias': '',
                                                      'field': 'g_themes',
                                                      'options': '',
                                                      'title': 'th\xc3\xa8me',
                                                      'visible': '0',
                                                      'width': '70'},
                                              21: {   'alias': '',
                                                      'field': 'g_chartreuses',
                                                      'options': '',
                                                      'title': 'chartreuses',
                                                      'visible': '0',
                                                      'width': '200'},
                                              22: {   'field': 'contenu',
                                                      'options': '',
                                                      'title': 'contenu',
                                                      'visible': 0,
                                                      'width': 100},
                                              23: {   'field': 'remarques',
                                                      'options': '',
                                                      'title': 'remarques',
                                                      'visible': '1',
                                                      'width': '40'},
                                              25: {   'alias': '',
                                                      'field': 'format',
                                                      'options': '',
                                                      'title': 'ann\xc3\xa9e',
                                                      'visible': 0,
                                                      'width': 50},
                                              27: {   'field': 'format',
                                                      'options': '',
                                                      'title': 'format',
                                                      'visible': '1',
                                                      'width': '20'},
                                              28: {   'alias': 'siecle = si\xc3\xa8cle',
                                                      'field': 'siecle as si\xc3\xa8cle',
                                                      'options': '',
                                                      'title': 'si\xc3\xa8cle',
                                                      'visible': 0,
                                                      'width': 30},
                                              29: {   'field': 'datemodification',
                                                      'options': '',
                                                      'title': 'datemodification',
                                                      'visible': 0,
                                                      'width': 70},
                                              30: {   }},
                                  'from': 'complete',
                                  'sort': None},
                  'complete_aut_ord': {   'cols': {   0: {   'field': 'complete.id_livre',
                                                             'visible': 0,
                                                             'width': 40},
                                                      1: {   'alias': '',
                                                             'field': 'section',
                                                             'options': '',
                                                             'visible': '1',
                                                             'width': '80'},
                                                      2: {   'field': 'section',
                                                             'visible': 0,
                                                             'width': 20},
                                                      3: {   'field': 'num',
                                                             'visible': 0,
                                                             'width': 40},
                                                      4: {   'field': 'exposant',
                                                             'visible': 0,
                                                             'width': 25},
                                                      5: {   'field': 'format',
                                                             'visible': 0,
                                                             'width': 20},
                                                      6: {   'field': 'notes',
                                                             'visible': 1,
                                                             'width': 40},
                                                      7: {   'field': 'localisation as local',
                                                             'visible': 1,
                                                             'width': 25},
                                                      8: {   'field': 'group_concat(distinct p1.nom) as auteur',
                                                             'visible': 1,
                                                             'width': 280},
                                                      9: {   'field': 'titre',
                                                             'visible': 0,
                                                             'width': 100},
                                                      10: {   'field': 'sous_titre',
                                                              'visible': 0,
                                                              'width': 50},
                                                      11: {   'field': 'complement',
                                                              'visible': 0,
                                                              'width': 50},
                                                      12: {   'field': 'titre',
                                                              'visible': 1,
                                                              'width': 750},
                                                      13: {   'field': 'traduction',
                                                              'visible': 0,
                                                              'width': 200},
                                                      14: {   'field': 'collaborateur',
                                                              'visible': 0,
                                                              'width': 200},
                                                      15: {   'field': 'vedette',
                                                              'visible': 0,
                                                              'width': 200},
                                                      16: {   'field': 'biographie',
                                                              'visible': 0,
                                                              'width': 200},
                                                      17: {   'field': 'complete.lieu',
                                                              'visible': 0,
                                                              'width': 40},
                                                      18: {   'field': 'editeur as \xc3\xa9diteur',
                                                              'visible': 1,
                                                              'width': 40},
                                                      19: {   'field': 'annee',
                                                              'visible': 0,
                                                              'width': 20},
                                                      20: {   'field': 'volumes',
                                                              'visible': 0,
                                                              'width': 40},
                                                      21: {   'field': 'pages',
                                                              'visible': 0,
                                                              'width': 40},
                                                      22: {   'field': 'hauteur',
                                                              'visible': 0,
                                                              'width': 40},
                                                      23: {   'field': 'illustrations',
                                                              'visible': 0,
                                                              'width': 70},
                                                      24: {   'field': 'langue',
                                                              'visible': 0,
                                                              'width': 200},
                                                      25: {   'field': 'theme as th\xc3\xa8me',
                                                              'visible': 0,
                                                              'width': 100},
                                                      26: {   'field': 'chartreuse',
                                                              'visible': 0,
                                                              'width': 200},
                                                      27: {   'field': 'contenu',
                                                              'visible': 0,
                                                              'width': 200},
                                                      28: {   'field': 'complete.remarques',
                                                              'visible': 0,
                                                              'width': 100},
                                                      29: {   'field': 'erreur',
                                                              'visible': 0,
                                                              'width': 50},
                                                      30: {   'field': 'temp as temporaire',
                                                              'visible': 0,
                                                              'width': 100},
                                                      31: {   'field': 'date',
                                                              'visible': 0,
                                                              'width': 30},
                                                      32: {   'field': 'annee as ann\xc3\xa9e',
                                                              'visible': 0,
                                                              'width': 20},
                                                      33: {   'field': 'siecle as si\xc3\xa8cle',
                                                              'visible': 0,
                                                              'width': 30},
                                                      34: {   'field': 'tri_cote',
                                                              'visible': 0,
                                                              'width': 70},
                                                      35: {   'field': 'compteur',
                                                              'visible': 0,
                                                              'width': 70},
                                                      36: {   'field': 'datemodification',
                                                              'visible': 0,
                                                              'width': 10}},
                                          'from': "complete         left join concerne c1 on (complete.id_livre=c1.id_livre and c1.fonction='auteur') left join personnes p1 using (id_personne)  ",
                                          'sort': {   0: {   'name': 'si\xc3\xa8cle nd',
                                                             'sort1': 'auteur',
                                                             'sort2': 'titre__etc'},
                                                      1: {   'name': 'tri_cote'},
                                                      2: {   'name': 'auteur',
                                                             'sort1': 'titre__etc',
                                                             'sort2': 'ann\xc3\xa9e dn'},
                                                      3: {   'name': 'titre__etc',
                                                             'sort1': 'ann\xc3\xa9e nd',
                                                             'sort2': 'id_livre'},
                                                      4: {   'name': 'ann\xc3\xa9e nd',
                                                             'sort1': 'auteur',
                                                             'sort2': 'titre__etc'},
                                                      5: None}}},
    'version': 2001,
    'words': {   'mots': {   'Exclude': '',
                             'central_def': 'completex',
                             'config_name': 'mots',
                             'fields': {   0: {   'field': 'titre'},
                                           1: {   'field': 'remarques'},
                                           2: {   'field': 'traduction'},
                                           3: {   'field': 'sous_titre'},
                                           4: {   'field': 'complement'}},
                             'id_type': 'id_mot',
                             'main_field': 'mot',
                             'table': 'mots',
                             'table_type': 'words'}},
    'xtabs': {   'chartreuses': {   'central_table': 'complete',
                                    'check': None,
                                    'cols': {   0: {   'detail': 'nom5',
                                                       'field': 'chartreuse',
                                                       'options': '',
                                                       'title': 'Chartreusexx',
                                                       'width': '150'},
                                                1: {   'detail': 'renvoi5',
                                                       'field': 'renvoi',
                                                       'options': '',
                                                       'title': '',
                                                       'width': '250'},
                                                2: {   'detail': 'historique5',
                                                       'field': 'historique',
                                                       'options': '',
                                                       'title': 'Historique',
                                                       'width': ''},
                                                3: {   'detail': '',
                                                       'field': '#',
                                                       'options': '',
                                                       'title': '',
                                                       'width': '40'}},
                                    'complement': '',
                                    'config_name': 'chartreuses',
                                    'details_def': 'normal',
                                    'entry': 'tapez5',
                                    'name': 'chartreuses',
                                    'options': 'r=1;n',
                                    'peripheral_table': 'chartreuses',
                                    'result_def': 'complete',
                                    'table_def': 'chartreuses',
                                    'treeview': 'clist5',
                                    'type': 'list'},
                 'chartreuses2': {   'central_table': 'complete',
                                     'check': None,
                                     'cols': {   0: {   'detail': 'nom5',
                                                        'field': 'chartreuse',
                                                        'options': '',
                                                        'title': 'Chartreuse',
                                                        'width': '150'},
                                                 1: {   'detail': 'renvoi5',
                                                        'field': 'renvoi',
                                                        'options': '',
                                                        'title': '',
                                                        'width': '250'},
                                                 2: {   'detail': 'historique5',
                                                        'field': 'historique',
                                                        'options': '',
                                                        'title': 'Historique',
                                                        'width': ''},
                                                 3: {   'detail': '',
                                                        'field': '#',
                                                        'options': '',
                                                        'title': '',
                                                        'width': '40'}},
                                     'complement': '',
                                     'config_name': 'chartreuses2',
                                     'details_def': 'normal',
                                     'entry': 'sp_type_chartreuses',
                                     'name': 'chartreuses2',
                                     'options': 'r=1;',
                                     'peripheral_table': 'chartreuses',
                                     'result_def': 'complete',
                                     'table_def': 'chartreuses',
                                     'treeview': 'sp_chartreuses',
                                     'type': 'list'},
                 'collections': {   'central_table': 'complete',
                                    'check': None,
                                    'cols': {   0: {   'detail': 'nom9',
                                                       'field': 'collection',
                                                       'options': '',
                                                       'title': 'Collection',
                                                       'width': '250'},
                                                1: {   'detail': 'annotation9',
                                                       'field': 'annotation',
                                                       'options': '',
                                                       'title': 'Annotation',
                                                       'width': '250'},
                                                2: {   'detail': '',
                                                       'field': '#',
                                                       'options': '',
                                                       'title': '',
                                                       'width': '40'}},
                                    'complement': '',
                                    'config_name': 'collections',
                                    'details_def': 'normal',
                                    'entry': 'tapez9',
                                    'name': 'collections',
                                    'options': 'n',
                                    'peripheral_table': 'collections',
                                    'result_def': 'complete',
                                    'table_def': 'collections',
                                    'treeview': 'clist9',
                                    'type': 'list'},
                 'collections2': {   'central_table': 'complete',
                                     'check': None,
                                     'cols': {   0: {   'detail': 'nom9',
                                                        'field': 'collection',
                                                        'options': '',
                                                        'title': 'Collection',
                                                        'width': '250'},
                                                 1: {   'detail': 'annotation9',
                                                        'field': 'annotation',
                                                        'options': '',
                                                        'title': 'Annotation',
                                                        'width': '250'},
                                                 2: {   'detail': '',
                                                        'field': '#',
                                                        'options': '',
                                                        'title': '',
                                                        'width': '40'}},
                                     'complement': '',
                                     'config_name': 'collections2',
                                     'details_def': 'normal',
                                     'entry': 'sp_type_collections',
                                     'name': 'collections2',
                                     'options': 'n',
                                     'peripheral_table': 'collections',
                                     'result_def': 'complete',
                                     'table_def': 'collections',
                                     'treeview': 'sp_collections',
                                     'type': 'list'},
                 'langues': {   'central_table': 'complete',
                                'check': None,
                                'cols': {   0: {   'detail': 'nom6',
                                                   'field': 'langue',
                                                   'options': '',
                                                   'title': 'Langue',
                                                   'width': '250'},
                                            1: {   'detail': 'commentaire6',
                                                   'field': 'commentaire',
                                                   'options': '',
                                                   'title': 'Commentaire',
                                                   'width': '100'},
                                            2: {   'detail': '',
                                                   'field': '#',
                                                   'options': '',
                                                   'title': '#',
                                                   'width': '40'}},
                                'complement': '',
                                'config_name': 'langues',
                                'details_def': 'normal',
                                'entry': 'tapez6',
                                'name': 'langues',
                                'options': '',
                                'peripheral_table': 'langues',
                                'result_def': 'complete',
                                'table_def': 'langues',
                                'treeview': 'clist6',
                                'type': 'list'},
                 'langues2': {   'central_table': 'complete',
                                 'check': None,
                                 'cols': {   0: {   'detail': 'nom6',
                                                    'field': 'langue',
                                                    'options': '',
                                                    'title': 'Langue',
                                                    'width': '250'},
                                             1: {   'detail': 'commentaire6',
                                                    'field': 'commentaire',
                                                    'options': '',
                                                    'title': 'Commentaire',
                                                    'width': '100'},
                                             2: {   'detail': '',
                                                    'field': '#',
                                                    'options': '',
                                                    'title': '',
                                                    'width': '40'}},
                                 'complement': '',
                                 'config_name': 'langues2',
                                 'details_def': 'normal',
                                 'entry': 'sp_type_language',
                                 'name': 'langues2',
                                 'options': '',
                                 'peripheral_table': 'langues',
                                 'result_def': 'complete',
                                 'table_def': 'langues',
                                 'treeview': 'sp_language',
                                 'type': 'list'},
                 'persons': {   'central_table': 'complete',
                                'check': {   0: {   'checkbox': 'check_pers_all',
                                                    'field': 'i_data_complete',
                                                    'name': 'tout'},
                                             1: {   'checkbox': 'check_pers_auteur',
                                                    'field': 'i_auteur',
                                                    'name': 'auteur'},
                                             2: {   'checkbox': 'check_pers_bio',
                                                    'field': 'i_biographie',
                                                    'name': 'biographie'},
                                             3: {   'checkbox': 'check_pers_etude',
                                                    'field': 'i_vedette',
                                                    'name': '\xc3\xa9tude'},
                                             4: {   'checkbox': 'check_pers_coll',
                                                    'field': 'i_collaborateur',
                                                    'name': 'collaborateur'}},
                                'cols': {   0: {   'detail': 'nom3',
                                                   'field': 'nom',
                                                   'options': '',
                                                   'title': 'Personne',
                                                   'width': '250'},
                                            1: {   'detail': 'renvoi3', 'field': 'renvoi'},
                                            2: {   'detail': 'presentation3',
                                                   'field': 'presentation',
                                                   'options': '',
                                                   'title': 'Pr\xc3\xa9sentation',
                                                   'width': '100'},
                                            3: {   'field': '#i_auteur',
                                                   'title': 'A',
                                                   'width': '40'},
                                            4: {   'field': '#i_collaborateur',
                                                   'title': 'C',
                                                   'width': '40'},
                                            5: {   'field': '#i_biographie',
                                                   'title': 'B',
                                                   'width': '40'},
                                            6: {   'field': '#i_vedette',
                                                   'title': 'V',
                                                   'width': '40'},
                                            7: {   'field': '#', 'title': 'T', 'width': '40'}},
                                'complement': '',
                                'config_name': 'persons',
                                'details_def': 'normal',
                                'entry': 'tapez3',
                                'name': 'persons',
                                'options': 'r=renvoi,n',
                                'peripheral_table': 'personnes',
                                'result_def': 'complete',
                                'table_def': 'personnesx',
                                'treeview': 'clist3',
                                'type': 'list'},
                 'persons2': {   'central_table': 'complete',
                                 'check': None,
                                 'cols': {   0: {   'detail': 'person_name',
                                                    'field': 'nom',
                                                    'title': 'Personne',
                                                    'width': '250'},
                                             1: {   'detail': 'renvoi3', 'field': 'renvoi'},
                                             2: {   'detail': 'person_presentation',
                                                    'field': 'presentation',
                                                    'title': 'Pr\xc3\xa9sentation',
                                                    'width': '100'},
                                             3: {   'field': '#i_auteur',
                                                    'title': 'A',
                                                    'width': '40'},
                                             4: {   'field': '#i_collaborateur',
                                                    'title': 'C',
                                                    'width': '40'},
                                             5: {   'field': '#i_biographie',
                                                    'title': 'B',
                                                    'width': '40'},
                                             6: {   'field': '#i_vedette',
                                                    'title': 'V',
                                                    'width': '40'},
                                             7: {   'field': '#', 'title': 'T', 'width': '40'}},
                                 'complement': '',
                                 'config_name': 'persons2',
                                 'details_def': 'normal',
                                 'entry': 'sp_type_persons',
                                 'name': 'persons2',
                                 'options': 'r=renvoi,n',
                                 'peripheral_table': 'personnes',
                                 'result_def': 'complete',
                                 'table_def': 'personnesx',
                                 'treeview': 'sp_persons',
                                 'type': 'list'},
                 'themes_list': {   'central_table': 'complete',
                                    'check': None,
                                    'cols': {   0: {   'detail': 'nom7',
                                                       'field': 'theme',
                                                       'options': '',
                                                       'title': 'Chartreuse',
                                                       'width': '250'},
                                                1: {   'field': '#',
                                                       'title': 'Compte',
                                                       'width': '30'},
                                                2: {   'detail': 'observations7',
                                                       'field': 'observations',
                                                       'options': '',
                                                       'title': '',
                                                       'width': ''},
                                                3: {   'detail': 'renvoi7',
                                                       'field': 'renvoi',
                                                       'options': '',
                                                       'title': '',
                                                       'width': ''},
                                                4: {   'detail': 'notes7',
                                                       'field': 'notes',
                                                       'options': '',
                                                       'title': 'Notes',
                                                       'width': '100'}},
                                    'complement': 'and theme not like "**%"',
                                    'config_name': 'themes_list',
                                    'details_def': 'normal',
                                    'entry': 'tapez7',
                                    'name': 'themes_list',
                                    'options': 'r=3,n',
                                    'peripheral_table': 'themes',
                                    'result_def': 'complete',
                                    'table_def': 'themes',
                                    'treeview': 'clist7',
                                    'type': 'list'},
                 'themes_list2': {   'central_table': 'complete',
                                     'check': None,
                                     'cols': {   0: {   'detail': 'themes_name',
                                                        'field': 'theme',
                                                        'title': 'Chartreuse',
                                                        'width': '250'},
                                                 1: {   'field': '#',
                                                        'title': 'Compte',
                                                        'width': '30'},
                                                 2: {   'detail': 'themes_observations',
                                                        'field': 'observations',
                                                        'title': '',
                                                        'width': ''},
                                                 3: {   'detail': 'themes_renvoi',
                                                        'field': 'renvoi',
                                                        'title': '',
                                                        'width': ''},
                                                 4: {   'detail': 'themes_notes',
                                                        'field': 'notes',
                                                        'title': 'Notes',
                                                        'width': '100'}},
                                     'complement': 'and theme not like "**%"',
                                     'config_name': 'themes_list2',
                                     'details_def': 'normal',
                                     'entry': 'sp_type_themes',
                                     'name': 'themes_list2',
                                     'options': 'r=3,n',
                                     'peripheral_table': 'themes',
                                     'result_def': 'complete',
                                     'table_def': 'themes',
                                     'treeview': 'sp_themes',
                                     'type': 'list'},
                 'themes_tree': {   'central_table': 'complete',
                                    'check': None,
                                    'cols': {   0: {   'detail': 'nom1',
                                                       'field': 'theme',
                                                       'title': 'Langue',
                                                       'width': '400'},
                                                1: {   'field': '#',
                                                       'title': 'Compte',
                                                       'width': '50'},
                                                2: {   'detail': 'observations1',
                                                       'field': 'observations',
                                                       'title': '',
                                                       'width': ''},
                                                3: {   'detail': '',
                                                       'field': 'couleur',
                                                       'options': '',
                                                       'title': '',
                                                       'width': ''}},
                                    'complement': '',
                                    'config_name': 'themes_tree',
                                    'details_def': 'normal',
                                    'entry': '',
                                    'name': 'themes_tree',
                                    'options': 'c=couleur;',
                                    'peripheral_table': 'themes',
                                    'result_def': 'complete',
                                    'table_def': 'themes',
                                    'treeview': 'clist1',
                                    'type': 'tree'},
                 'themes_tree2': {   'central_table': 'complete',
                                     'check': None,
                                     'cols': {   0: {   'detail': 'nom1',
                                                        'field': 'theme',
                                                        'title': 'Langue',
                                                        'width': '400'},
                                                 1: {   'field': '#',
                                                        'title': 'Compte',
                                                        'width': '50'},
                                                 2: {   'detail': 'observations1',
                                                        'field': 'observations',
                                                        'title': '',
                                                        'width': ''},
                                                 3: {   'detail': '',
                                                        'field': 'couleur',
                                                        'options': '',
                                                        'title': '',
                                                        'width': ''}},
                                     'complement': '',
                                     'config_name': 'themes_tree2',
                                     'details_def': 'normal',
                                     'entry': '',
                                     'name': 'themes_tree2',
                                     'options': 'c=couleur;',
                                     'peripheral_table': 'themes',
                                     'result_def': 'complete',
                                     'table_def': 'themes',
                                     'treeview': 'sp_themes_tree',
                                     'type': 'tree'},
                 'words': {   'central_table': 'complete',
                              'check': None,
                              'cols': {   0: {   'field': 'id_mot'},
                                          1: {   'field': 'mot', 'title': 'Mot', 'width': '150'},
                                          2: {   'detail': '',
                                                 'field': '#i_titre',
                                                 'title': 'Titre',
                                                 'width': '50'},
                                          3: {   'detail': '',
                                                 'field': '#i_complement',
                                                 'title': 'Compl\xc3\xa9ment',
                                                 'width': '50'},
                                          4: {   'detail': '',
                                                 'field': '#i_traduction',
                                                 'title': 'Traduction',
                                                 'width': '50'},
                                          5: {   'detail': '',
                                                 'field': '#i_contenu',
                                                 'title': 'Contenu',
                                                 'width': '50'},
                                          6: {   'detail': '',
                                                 'field': '#i_remarques',
                                                 'title': 'Remarques',
                                                 'width': '50'},
                                          7: {   'detail': '',
                                                 'field': '#',
                                                 'options': '',
                                                 'title': 'T',
                                                 'width': '50'}},
                              'complement': '',
                              'config_name': 'words',
                              'details_def': 'normal',
                              'entry': 'tapez8',
                              'name': 'words',
                              'options': 'n',
                              'peripheral_table': 'mots',
                              'result_def': 'complete',
                              'table_def': 'mots',
                              'treeview': 'clist8',
                              'type': 'list'},
                 'words2': {   'central_table': 'complete',
                               'check': None,
                               'cols': {   0: {   'field': 'id_mot'},
                                           1: {   'field': 'mot', 'title': 'Mot', 'width': '150'},
                                           2: {   'detail': '',
                                                  'field': '#i_titre',
                                                  'title': 'Titre',
                                                  'width': '50'},
                                           3: {   'detail': '',
                                                  'field': '#i_complement',
                                                  'title': 'Compl\xc3\xa9ment',
                                                  'width': '50'},
                                           4: {   'detail': '',
                                                  'field': '#i_traduction',
                                                  'title': 'Traduction',
                                                  'width': '50'},
                                           5: {   'detail': '',
                                                  'field': '#i_contenu',
                                                  'title': 'Contenu',
                                                  'width': '50'},
                                           6: {   'detail': '',
                                                  'field': '#i_remarques',
                                                  'title': 'Remarques',
                                                  'width': '50'}},
                               'complement': '',
                               'config_name': 'words2',
                               'details_def': 'normal',
                               'entry': 'sp_type_words',
                               'name': 'words2',
                               'options': 'n',
                               'peripheral_table': 'mots',
                               'result_def': 'complete',
                               'table_def': 'mots',
                               'treeview': 'sp_words',
                               'type': 'list'}}}
